-- ========================================= KEF-OSL  01.05.2014 ===========================================
-- Buisness Class
insert into Bookings(timeOfBooking,paymentType,cardIssuedBy,cardholdersName,flightCode,classID)values('2014-04-23',1,'Mastercard','Theodor Fransson',1,1);						
insert into Bookings(timeOfBooking,paymentType,cardIssuedBy,cardholdersName,flightCode,classID)values('2014-04-30',1,'Diners Club','Kjetil Amundsen',1,1);
insert into Bookings(timeOfBooking,paymentType,cardIssuedBy,cardholdersName,flightCode,classID)values('2014-04-27',1,'American Express','Andreas Rasmussen',1,1);
insert into Bookings(timeOfBooking,paymentType,cardIssuedBy,cardholdersName,flightCode,classID)values('2014-04-29',1,'VISA','Hjördís Orradóttir',1,1); 
insert into Bookings(timeOfBooking,paymentType,cardIssuedBy,cardholdersName,flightCode,classID)values('2014-04-29',1,'Mastercard','Ísak Leósson',1,1);
insert into Bookings(timeOfBooking,paymentType,cardIssuedBy,cardholdersName,flightCode,classID)values('2014-04-25',1,'VISA','Jóhann Kristinsson',1,1);
insert into Bookings(timeOfBooking,paymentType,cardIssuedBy,cardholdersName,flightCode,classID)values('2014-04-17',1,'VISA','Andri Valsson',1,1);
insert into Bookings(timeOfBooking,paymentType,cardIssuedBy,cardholdersName,flightCode,classID)values('2014-04-16',1,'VISA','Friðrik Hlynsson',1,1);
insert into Bookings(timeOfBooking,paymentType,cardIssuedBy,cardholdersName,flightCode,classID)values('2014-04-13',1,'VISA','Arnar Orrason',1,1); 
insert into Bookings(timeOfBooking,paymentType,cardIssuedBy,cardholdersName,flightCode,classID)values('2014-04-07',1,'Diners Club','Aeki Group AS',1,1);							
insert into Bookings(timeOfBooking,paymentType,cardIssuedBy,cardholdersName,flightCode,classID)values('2014-04-06',1,'VISA','Tuverud Partners AG',1,1);							
insert into Bookings(timeOfBooking,paymentType,cardIssuedBy,cardholdersName,flightCode,classID)values('2014-04-05',1,'Mastercard','Milljónafjelagið ehf',1,1);					
-- Economy Class
insert into Bookings(timeOfBooking,paymentType,cardIssuedBy,cardholdersName,flightCode,classID)values('2014-04-03',1,'VISA','Nathalie Johansson',1,3);
insert into Bookings(timeOfBooking,paymentType,cardIssuedBy,cardholdersName,flightCode,classID)values('2014-04-01',1,'VISA','María Birgisdóttir',1,3);
insert into Bookings(timeOfBooking,paymentType,cardIssuedBy,cardholdersName,flightCode,classID)values('2014-04-07',1,'Mastercard',' Knut Vik',1,3);
insert into Bookings(timeOfBooking,paymentType,cardIssuedBy,cardholdersName,flightCode,classID)values('2014-04-21',1,'Diners Club','Bjørn Eide',1,3);
insert into Bookings(timeOfBooking,paymentType,cardIssuedBy,cardholdersName,flightCode,classID)values('2014-04-12',1,'Mastercard',' Sindre Olsen',1,3);							
insert into Bookings(timeOfBooking,paymentType,cardIssuedBy,cardholdersName,flightCode,classID)values('2014-04-22',1,'VISA','Halldór Jóhannsson',1,3); 
insert into Bookings(timeOfBooking,paymentType,cardIssuedBy,cardholdersName,flightCode,classID)values('2014-04-19',1,'VISA','Ingvar Brekason',1,3); 
insert into Bookings(timeOfBooking,paymentType,cardIssuedBy,cardholdersName,flightCode,classID)values('2014-04-19',1,'Mastercard','Snorri Birgisson',1,3); 
insert into Bookings(timeOfBooking,paymentType,cardIssuedBy,cardholdersName,flightCode,classID)values('2014-04-03',1,'Mastercard','Margrét Benediktsdóttir',1,3);					
insert into Bookings(timeOfBooking,paymentType,cardIssuedBy,cardholdersName,flightCode,classID)values('2014-04-26',1,'VISA','Gunnar Magnússon',1,3);							
insert into Bookings(timeOfBooking,paymentType,cardIssuedBy,cardholdersName,flightCode,classID)values('2014-04-14',1,'VISA','Sigurður Þorsteinsson',1,3); 
insert into Bookings(timeOfBooking,paymentType,cardIssuedBy,cardholdersName,flightCode,classID)values('2014-04-11',1,'VISA','Magnús Ingvarsson',1,3); 
insert into Bookings(timeOfBooking,paymentType,cardIssuedBy,cardholdersName,flightCode,classID)values('2014-04-07',1,'VISA','Margrét Jónsdóttir',1,3);
insert into Bookings(timeOfBooking,paymentType,cardIssuedBy,cardholdersName,flightCode,classID)values('2014-04-27',1,'Mastercard','Ósk Darradóttir',1,3);
insert into Bookings(timeOfBooking,paymentType,cardIssuedBy,cardholdersName,flightCode,classID)values('2014-04-03',1,'VISA','Herdís Guðlaugsdóttir',1,3); 
insert into Bookings(timeOfBooking,paymentType,cardIssuedBy,cardholdersName,flightCode,classID)values('2014-04-22',1,'Mastercard','Roar Pedersen',1,3);
insert into Bookings(timeOfBooking,paymentType,cardIssuedBy,cardholdersName,flightCode,classID)values('2014-04-01',1,'VISA','Astrid Jakobsen',1,3);
insert into Bookings(timeOfBooking,paymentType,cardIssuedBy,cardholdersName,flightCode,classID)values('2014-04-04',1,'Mastercard','Svein Karlsen',1,3);
insert into Bookings(timeOfBooking,paymentType,cardIssuedBy,cardholdersName,flightCode,classID)values('2014-04-03',1,'VISA','Solveig Sørensen',1,3);
insert into Bookings(timeOfBooking,paymentType,cardIssuedBy,cardholdersName,flightCode,classID)values('2014-04-06',1,'Mastercard','Kjell Martinsen',1,3);
insert into Bookings(timeOfBooking,paymentType,cardIssuedBy,cardholdersName,flightCode,classID)values('2014-04-06',1,'VISA','Anne Johannessen',1,3);
insert into Bookings(timeOfBooking,paymentType,cardIssuedBy,cardholdersName,flightCode,classID)values('2014-04-15',1,'Mastercard','Adam Larsson',1,3); 
insert into Bookings(timeOfBooking,paymentType,cardIssuedBy,cardholdersName,flightCode,classID)values('2014-04-15',1,'VISA','Daniel Olsson',1,3); 
insert into Bookings(timeOfBooking,paymentType,cardIssuedBy,cardholdersName,flightCode,classID)values('2014-04-15',1,'VISA','Vincent Nilsson',1,3); 
insert into Bookings(timeOfBooking,paymentType,cardIssuedBy,cardholdersName,flightCode,classID)values('2014-04-16',1,'VISA','Klara Björk',1,3);	
insert into Bookings(timeOfBooking,paymentType,cardIssuedBy,cardholdersName,flightCode,classID)values('2014-04-18',1,'VISA','Adam Johansson',1,3); 
insert into Bookings(timeOfBooking,paymentType,cardIssuedBy,cardholdersName,flightCode,classID)values('2014-04-19',1,'VISA','Freja Karlsson',1,3);	
insert into Bookings(timeOfBooking,paymentType,cardIssuedBy,cardholdersName,flightCode,classID)values('2014-04-11',1,'VISA','Liam Hansson',1,3);	
insert into Bookings(timeOfBooking,paymentType,cardIssuedBy,cardholdersName,flightCode,classID)values('2014-04-09',1,'Mastercard','Freja Karlsson',1,3);	 
insert into Bookings(timeOfBooking,paymentType,cardIssuedBy,cardholdersName,flightCode,classID)values('2014-04-09',1,'Diners Club','Alfred Axelsson',1,3);	 
insert into Bookings(timeOfBooking,paymentType,cardIssuedBy,cardholdersName,flightCode,classID)values('2014-04-04',1,'VISA','Ella Henriksson',1,3);	 
insert into Bookings(timeOfBooking,paymentType,cardIssuedBy,cardholdersName,flightCode,classID)values('2014-04-03',1,'VISA','Eddie Lindström',1,3);	 
insert into Bookings(timeOfBooking,paymentType,cardIssuedBy,cardholdersName,flightCode,classID)values('2014-04-03',1,'VISA','Jasmine Berg',1,3);  
insert into Bookings(timeOfBooking,paymentType,cardIssuedBy,cardholdersName,flightCode,classID)values('2014-04-06',1,'American Express','Noah Olsson',1,3);	 
insert into Bookings(timeOfBooking,paymentType,cardIssuedBy,cardholdersName,flightCode,classID)values('2014-04-27',1,'VISA','Emil Jönsson',1,3);	 
insert into Bookings(timeOfBooking,paymentType,cardIssuedBy,cardholdersName,flightCode,classID)values('2014-04-27',1,'Diners Club','Petter Knudsen',1,3);
insert into Bookings(timeOfBooking,paymentType,cardIssuedBy,cardholdersName,flightCode,classID)values('2014-04-21',1,'VISA','Anna Hanssen',1,3);
insert into Bookings(timeOfBooking,paymentType,cardIssuedBy,cardholdersName,flightCode,classID)values('2014-04-19',1,'VISA','Terje Gundersen',1,3);
insert into Bookings(timeOfBooking,paymentType,cardIssuedBy,cardholdersName,flightCode,classID)values('2014-04-06',1,'VISA','Silje Jacobsen',1,3);
insert into Bookings(timeOfBooking,paymentType,cardIssuedBy,cardholdersName,flightCode,classID)values('2014-04-08',1,'VISA','Jan Kristiansen',1,3);
insert into Bookings(timeOfBooking,paymentType,cardIssuedBy,cardholdersName,flightCode,classID)values('2014-04-12',1,'Mastercard','Anna Fredriksen',1,3);
insert into Bookings(timeOfBooking,paymentType,cardIssuedBy,cardholdersName,flightCode,classID)values('2014-04-01',1,'Mastercard','Anne Myhre',1,3);
insert into Bookings(timeOfBooking,paymentType,cardIssuedBy,cardholdersName,flightCode,classID)values('2014-04-01',1,'Mastercard','Kari Tveit',1,3);
insert into Bookings(timeOfBooking,paymentType,cardIssuedBy,cardholdersName,flightCode,classID)values('2014-04-09',1,'VISA','Stine Jensen',1,3);
insert into Bookings(timeOfBooking,paymentType,cardIssuedBy,cardholdersName,flightCode,classID)values('2014-04-22',1,'VISA','Turid Andersen',1,3);
insert into Bookings(timeOfBooking,paymentType,cardIssuedBy,cardholdersName,flightCode,classID)values('2014-04-28',1,'American Express','Frank Haugen',1,3);
insert into Bookings(timeOfBooking,paymentType,cardIssuedBy,cardholdersName,flightCode,classID)values('2014-04-28',1,'VISA','Sander Eriksen',1,3);
insert into Bookings(timeOfBooking,paymentType,cardIssuedBy,cardholdersName,flightCode,classID)values('2014-04-16',1,'VISA','Svein Knudsen',1,3);
insert into Bookings(timeOfBooking,paymentType,cardIssuedBy,cardholdersName,flightCode,classID)values('2014-04-15',1,'American Express','Inger Moen',1,3);
insert into Bookings(timeOfBooking,paymentType,cardIssuedBy,cardholdersName,flightCode,classID)values('2014-04-15',1,'VISA','Anne Bakken',1,3);
insert into Bookings(timeOfBooking,paymentType,cardIssuedBy,cardholdersName,flightCode,classID)values('2014-04-17',1,'VISA','Berit Ruud',1,3);
insert into Bookings(timeOfBooking,paymentType,cardIssuedBy,cardholdersName,flightCode,classID)values('2014-04-23',1,'VISA','Line Lien',1,3);
insert into Bookings(timeOfBooking,paymentType,cardIssuedBy,cardholdersName,flightCode,classID)values('2014-04-14',1,'VISA','Jorunn Ødegård',1,3);
insert into Bookings(timeOfBooking,paymentType,cardIssuedBy,cardholdersName,flightCode,classID)values('2014-04-24',1,'VISA','Line Kristoffersen',1,3);
insert into Bookings(timeOfBooking,paymentType,cardIssuedBy,cardholdersName,flightCode,classID)values('2014-04-11',1,'VISA','Hilde Larsen',1,3);
insert into Bookings(timeOfBooking,paymentType,cardIssuedBy,cardholdersName,flightCode,classID)values('2014-04-21',1,'Mastercard','Kari Ahmed',1,3);
insert into Bookings(timeOfBooking,paymentType,cardIssuedBy,cardholdersName,flightCode,classID)values('2014-04-22',1,'VISA','Kristian Strand',1,3);
insert into Bookings(timeOfBooking,paymentType,cardIssuedBy,cardholdersName,flightCode,classID)values('2014-04-30',1,'VISA','Eivind Pedersen',1,3);
insert into Bookings(timeOfBooking,paymentType,cardIssuedBy,cardholdersName,flightCode,classID)values('2014-04-30',1,'American Express','Pål Johansen',1,3);
insert into Bookings(timeOfBooking,paymentType,cardIssuedBy,cardholdersName,flightCode,classID)values('2014-04-12',1,'VISA','Marit Gulbrandsen',1,3);
insert into Bookings(timeOfBooking,paymentType,cardIssuedBy,cardholdersName,flightCode,classID)values('2014-04-05',1,'VISA','Ida Moe',1,3);
insert into Bookings(timeOfBooking,paymentType,cardIssuedBy,cardholdersName,flightCode,classID)values('2014-04-03',1,'VISA','Malin Gundersen',1,3);
insert into Bookings(timeOfBooking,paymentType,cardIssuedBy,cardholdersName,flightCode,classID)values('2014-04-02',1,'Mastercard','Aud Pedersen',1,3);
insert into Bookings(timeOfBooking,paymentType,cardIssuedBy,cardholdersName,flightCode,classID)values('2014-04-20',1,'VISA','Ragnhild Berge',1,3);
insert into Bookings(timeOfBooking,paymentType,cardIssuedBy,cardholdersName,flightCode,classID)values('2014-04-20',1,'Diners Club','Arne Mathisen',1,3);
insert into Bookings(timeOfBooking,paymentType,cardIssuedBy,cardholdersName,flightCode,classID)values('2014-04-10',1,'Mastercard','Trond Johansen',1,3);
insert into Bookings(timeOfBooking,paymentType,cardIssuedBy,cardholdersName,flightCode,classID)values('2014-04-21',1,'Mastercard','Frank Jensen',1,3);
insert into Bookings(timeOfBooking,paymentType,cardIssuedBy,cardholdersName,flightCode,classID)values('2014-04-17',1,'VISA','Ingrid Haugen',1,3);
insert into Bookings(timeOfBooking,paymentType,cardIssuedBy,cardholdersName,flightCode,classID)values('2014-04-09',1,'VISA','Line Hansen',1,3);
insert into Bookings(timeOfBooking,paymentType,cardIssuedBy,cardholdersName,flightCode,classID)values('2014-04-29',1,'VISA','Karoline Iversen',1,3);
insert into Bookings(timeOfBooking,paymentType,cardIssuedBy,cardholdersName,flightCode,classID)values('2014-04-27',1,'VISA','Harald Haug',1,3);
insert into Bookings(timeOfBooking,paymentType,cardIssuedBy,cardholdersName,flightCode,classID)values('2014-04-14',1,'VISA','Terje Johnsen',1,3);
insert into Bookings(timeOfBooking,paymentType,cardIssuedBy,cardholdersName,flightCode,classID)values('2014-04-18',1,'VISA','Kristoffer Bakke',1,3);
insert into Bookings(timeOfBooking,paymentType,cardIssuedBy,cardholdersName,flightCode,classID)values('2014-04-10',1,'VISA','Kari Hansen',1,3);
insert into Bookings(timeOfBooking,paymentType,cardIssuedBy,cardholdersName,flightCode,classID)values('2014-04-20',1,'VISA','Cecilie Pedersen',1,3);
insert into Bookings(timeOfBooking,paymentType,cardIssuedBy,cardholdersName,flightCode,classID)values('2014-04-10',1,'Mastercard','Martin Johnsen',1,3);
insert into Bookings(timeOfBooking,paymentType,cardIssuedBy,cardholdersName,flightCode,classID)values('2014-04-21',1,'American Express','Ingibjörg Ívarsdóttir',1,3); 
insert into Bookings(timeOfBooking,paymentType,cardIssuedBy,cardholdersName,flightCode,classID)values('2014-04-22',1,'Diners Club','Eva Stefánsdóttir',1,3);
insert into Bookings(timeOfBooking,paymentType,cardIssuedBy,cardholdersName,flightCode,classID)values('2014-04-22',1,'Mastercard','Sigríður Birgisdóttir',1,3);
insert into Bookings(timeOfBooking,paymentType,cardIssuedBy,cardholdersName,flightCode,classID)values('2014-04-22',1,'VISA','Margrét Axelsdóttir',1,3); 
insert into Bookings(timeOfBooking,paymentType,cardIssuedBy,cardholdersName,flightCode,classID)values('2014-04-04',1,'VISA','Marín Vilhjálmsdóttir',1,3);
insert into Bookings(timeOfBooking,paymentType,cardIssuedBy,cardholdersName,flightCode,classID)values('2014-04-12',1,'VISA','Helga Þorsteinsdóttir',1,3);
insert into Bookings(timeOfBooking,paymentType,cardIssuedBy,cardholdersName,flightCode,classID)values('2014-04-05',1,'Mastercard','Sigrún Eyþórsdóttir',1,3); 
insert into Bookings(timeOfBooking,paymentType,cardIssuedBy,cardholdersName,flightCode,classID)values('2014-04-05',1,'VISA','Lilja Tryggvadóttir',1,3);
insert into Bookings(timeOfBooking,paymentType,cardIssuedBy,cardholdersName,flightCode,classID)values('2014-04-17',1,'Mastercard','Sigríður Jónsdóttir',1,3); 
insert into Bookings(timeOfBooking,paymentType,cardIssuedBy,cardholdersName,flightCode,classID)values('2014-04-09',1,'Mastercard','Sigríður Þorsteinsdóttir',1,3); 
insert into Bookings(timeOfBooking,paymentType,cardIssuedBy,cardholdersName,flightCode,classID)values('2014-04-30',1,'Mastercard','Sigrún Grétarsdóttir',1,3); 
insert into Bookings(timeOfBooking,paymentType,cardIssuedBy,cardholdersName,flightCode,classID)values('2014-04-21',1,'Mastercard','Þórunn Andradóttir',1,3); 
insert into Bookings(timeOfBooking,paymentType,cardIssuedBy,cardholdersName,flightCode,classID)values('2014-04-17',1,'VISA','Kristín Birkisdóttir',1,3); 
insert into Bookings(timeOfBooking,paymentType,cardIssuedBy,cardholdersName,flightCode,classID)values('2014-04-11',1,'Mastercard','Auður Sveinsdóttir',1,3); 
insert into Bookings(timeOfBooking,paymentType,cardIssuedBy,cardholdersName,flightCode,classID)values('2014-04-10',1,'Mastercard','Ragnhildur Óskarsdóttir',1,3); 
insert into Bookings(timeOfBooking,paymentType,cardIssuedBy,cardholdersName,flightCode,classID)values('2014-04-29',1,'VISA','Áslaug Jónasdóttir',1,3); 
insert into Bookings(timeOfBooking,paymentType,cardIssuedBy,cardholdersName,flightCode,classID)values('2014-04-30',1,'Mastercard','Ingibjörg Guðjónsdóttir',1,3); 
insert into Bookings(timeOfBooking,paymentType,cardIssuedBy,cardholdersName,flightCode,classID)values('2014-04-28',1,'VISA','Hrafnhildur Þorvaldsdóttir',1,3);
insert into Bookings(timeOfBooking,paymentType,cardIssuedBy,cardholdersName,flightCode,classID)values('2014-04-26',1,'Mastercard','Helga Sveinsdóttir',1,3); 	
insert into Bookings(timeOfBooking,paymentType,cardIssuedBy,cardholdersName,flightCode,classID)values('2014-04-26',1,'VISA','Ingibjörg Eiríksdóttir',1,3); 
insert into Bookings(timeOfBooking,paymentType,cardIssuedBy,cardholdersName,flightCode,classID)values('2014-04-24',1,'Diners Club','Guðrún Sveinsdóttir',1,3);
insert into Bookings(timeOfBooking,paymentType,cardIssuedBy,cardholdersName,flightCode,classID)values('2014-04-24',1,'Diners Club','Ragnheiður Ægisdóttir',1,3);
insert into Bookings(timeOfBooking,paymentType,cardIssuedBy,cardholdersName,flightCode,classID)values('2014-04-01',1,'VISA','Kristín Gunnlaugsdóttir',1,3);
insert into Bookings(timeOfBooking,paymentType,cardIssuedBy,cardholdersName,flightCode,classID)values('2014-04-04',1,'Mastercard','Brynja Birkisdóttir',1,3);
insert into Bookings(timeOfBooking,paymentType,cardIssuedBy,cardholdersName,flightCode,classID)values('2014-04-24',1,'VISA','Steinn Halldórsson',1,3);
insert into Bookings(timeOfBooking,paymentType,cardIssuedBy,cardholdersName,flightCode,classID)values('2014-04-25',1,'VISA','Freyr Guðnason',1,3);
insert into Bookings(timeOfBooking,paymentType,cardIssuedBy,cardholdersName,flightCode,classID)values('2014-04-25',1,'VISA','Gunnar Magnússon',1,3);
insert into Bookings(timeOfBooking,paymentType,cardIssuedBy,cardholdersName,flightCode,classID)values('2014-04-11',1,'Mastercard','Axel Jóhannesson',1,3);
insert into Bookings(timeOfBooking,paymentType,cardIssuedBy,cardholdersName,flightCode,classID)values('2014-04-03',1,'VISA','Óli Bragason',1,3); 
insert into Bookings(timeOfBooking,paymentType,cardIssuedBy,cardholdersName,flightCode,classID)values('2014-04-01',1,'VISA','Jón Hlynsson',1,3);
insert into Bookings(timeOfBooking,paymentType,cardIssuedBy,cardholdersName,flightCode,classID)values('2014-04-19',1,'Mastercard','Bjarni Jóhannsson',1,3); 
insert into Bookings(timeOfBooking,paymentType,cardIssuedBy,cardholdersName,flightCode,classID)values('2014-04-19',1,'VISA','Jan Kristiansen',1,3);  
insert into Bookings(timeOfBooking,paymentType,cardIssuedBy,cardholdersName,flightCode,classID)values('2014-04-23',1,'American Express','Anders Haugland',1,3); 
insert into Bookings(timeOfBooking,paymentType,cardIssuedBy,cardholdersName,flightCode,classID)values('2014-04-26',1,'VISA','Kristian Berg',1,3);  
insert into Bookings(timeOfBooking,paymentType,cardIssuedBy,cardholdersName,flightCode,classID)values('2014-04-27',1,'Mastercard','Per Andersen',1,3);  
insert into Bookings(timeOfBooking,paymentType,cardIssuedBy,cardholdersName,flightCode,classID)values('2014-04-19',1,'Mastercard','Kristín Birgisdóttir',1,3); 
insert into Bookings(timeOfBooking,paymentType,cardIssuedBy,cardholdersName,flightCode,classID)values('2014-04-14',1,'Mastercard','Gunnar Magnússon',1,3); 
insert into Bookings(timeOfBooking,paymentType,cardIssuedBy,cardholdersName,flightCode,classID)values('2014-04-10',1,'VISA','Gísli Smárason',1,3);
insert into Bookings(timeOfBooking,paymentType,cardIssuedBy,cardholdersName,flightCode,classID)values('2014-04-24',1,'VISA','Sveinn Guðjónsson',1,3);
insert into Bookings(timeOfBooking,paymentType,cardIssuedBy,cardholdersName,flightCode,classID)values('2014-04-30',1,'VISA','Ómar Ívarsson',1,3); 
insert into Bookings(timeOfBooking,paymentType,cardIssuedBy,cardholdersName,flightCode,classID)values('2014-04-14',1,'Diners Club','María Grétarsdóttir',1,3); 
insert into Bookings(timeOfBooking,paymentType,cardIssuedBy,cardholdersName,flightCode,classID)values('2014-04-27',1,'VISA','Knattspyrnufélagið Þreyttur',1,3); 

-- ========================================= OSL-KEF  01.05.2014 ===========================================
-- First Class
insert into Bookings(timeOfBooking,paymentType,cardIssuedBy,cardholdersName,flightCode,classID)values('2014-04-18',1,'VISA','Tindra Nyström',32,1); 
insert into Bookings(timeOfBooking,paymentType,cardIssuedBy,cardholdersName,flightCode,classID)values('2014-04-06',1,'VISA','Vilhelm Persson',32,1); 
insert into Bookings(timeOfBooking,paymentType,cardIssuedBy,cardholdersName,flightCode,classID)values('2014-04-26',1,'VISA','August Bengtsson',32,1); 
insert into Bookings(timeOfBooking,paymentType,cardIssuedBy,cardholdersName,flightCode,classID)values('2014-04-29',1,'VISA','Benjamin Arvidsson',32,1); 
insert into Bookings(timeOfBooking,paymentType,cardIssuedBy,cardholdersName,flightCode,classID)values('2014-04-05',1,'Mastercard','Erik Svensson',32,1);
insert into Bookings(timeOfBooking,paymentType,cardIssuedBy,cardholdersName,flightCode,classID)values('2014-04-09',1,'Mastercard','Elias Abrahamsson',32,1);
insert into Bookings(timeOfBooking,paymentType,cardIssuedBy,cardholdersName,flightCode,classID)values('2014-04-02',1,'VISA','Olivia Nordström',32,1);
insert into Bookings(timeOfBooking,paymentType,cardIssuedBy,cardholdersName,flightCode,classID)values('2014-04-22',1,'VISA','Edvard Lundqvist',32,1);
insert into Bookings(timeOfBooking,paymentType,cardIssuedBy,cardholdersName,flightCode,classID)values('2014-04-07',1,'VISA','Hjalmar Larsson',32,1); 
insert into Bookings(timeOfBooking,paymentType,cardIssuedBy,cardholdersName,flightCode,classID)values('2014-04-19',1,'American Express','Sigge Johansson',32,1); 
insert into Bookings(timeOfBooking,paymentType,cardIssuedBy,cardholdersName,flightCode,classID)values('2014-04-02',1,'VISA','Jan Hansen',32,1);  
insert into Bookings(timeOfBooking,paymentType,cardIssuedBy,cardholdersName,flightCode,classID)values('2014-04-20',1,'Mastercard','Anne Nilsen',32,1); 
insert into Bookings(timeOfBooking,paymentType,cardIssuedBy,cardholdersName,flightCode,classID)values('2014-04-23',1,'Mastercard','Maria Haugland',32,1); 
insert into Bookings(timeOfBooking,paymentType,cardIssuedBy,cardholdersName,flightCode,classID)values('2014-04-15',1,'American Express','Anne Hagen',32,1); 
insert into Bookings(timeOfBooking,paymentType,cardIssuedBy,cardholdersName,flightCode,classID)values('2014-04-08',1,'VISA','Hans Olsen',32,1); 
insert into Bookings(timeOfBooking,paymentType,cardIssuedBy,cardholdersName,flightCode,classID)values('2014-04-11',1,'VISA','Karin Ellingsen',32,1); 
insert into Bookings(timeOfBooking,paymentType,cardIssuedBy,cardholdersName,flightCode,classID)values('2014-04-23',1,'Diners Club','Kristian Sandvik',32,1); 
insert into Bookings(timeOfBooking,paymentType,cardIssuedBy,cardholdersName,flightCode,classID)values('2014-04-24',1,'VISA','Ari Antonsson',32,1); 
insert into Bookings(timeOfBooking,paymentType,cardIssuedBy,cardholdersName,flightCode,classID)values('2014-04-25',1,'Mastercard','Axel Valdimarsson',32,1);
insert into Bookings(timeOfBooking,paymentType,cardIssuedBy,cardholdersName,flightCode,classID)values('2014-04-04',1,'Mastercard','Bjarni Hjaltason',32,1); 
insert into Bookings(timeOfBooking,paymentType,cardIssuedBy,cardholdersName,flightCode,classID)values('2014-04-02',1,'VISA','Kristín Guðmundsdóttir',32,1); 
insert into Bookings(timeOfBooking,paymentType,cardIssuedBy,cardholdersName,flightCode,classID)values('2014-04-01',1,'Mastercard','Breki Hilmarsson',32,1); 
insert into Bookings(timeOfBooking,paymentType,cardIssuedBy,cardholdersName,flightCode,classID)values('2014-04-18',1,'Mastercard','Jakob Björnsson',32,1); 
insert into Bookings(timeOfBooking,paymentType,cardIssuedBy,cardholdersName,flightCode,classID)values('2014-04-10',1,'Mastercard','Sævar Andrason',32,1); 
-- Economy Class
insert into Bookings(timeOfBooking,paymentType,cardIssuedBy,cardholdersName,flightCode,classID)values('2014-04-03',1,'VISA','Olivia Karlsson',32,3); 	
insert into Bookings(timeOfBooking,paymentType,cardIssuedBy,cardholdersName,flightCode,classID)values('2014-04-08',1,'VISA','Maja Pettersson',32,3); 
insert into Bookings(timeOfBooking,paymentType,cardIssuedBy,cardholdersName,flightCode,classID)values('2014-04-28',1,'VISA','Leo Lindgren',32,3); 
insert into Bookings(timeOfBooking,paymentType,cardIssuedBy,cardholdersName,flightCode,classID)values('2014-04-20',1,'Mastercard','Ella Sandström',32,3); 
insert into Bookings(timeOfBooking,paymentType,cardIssuedBy,cardholdersName,flightCode,classID)values('2014-04-19',1,'VISA','Frank Nilsson',32,3); 
insert into Bookings(timeOfBooking,paymentType,cardIssuedBy,cardholdersName,flightCode,classID)values('2014-04-29',1,'Mastercard','Emma Persson',32,3); 
insert into Bookings(timeOfBooking,paymentType,cardIssuedBy,cardholdersName,flightCode,classID)values('2014-04-11',1,'American Express','Elsa Svensson',32,3); 
insert into Bookings(timeOfBooking,paymentType,cardIssuedBy,cardholdersName,flightCode,classID)values('2014-04-03',1,'VISA','Jonathan Andersson',32,3); 
insert into Bookings(timeOfBooking,paymentType,cardIssuedBy,cardholdersName,flightCode,classID)values('2014-04-18',1,'Mastercard','Theodor Wallin',32,3); 
insert into Bookings(timeOfBooking,paymentType,cardIssuedBy,cardholdersName,flightCode,classID)values('2014-04-02',1,'VISA','Filip Bergström',32,3); 
insert into Bookings(timeOfBooking,paymentType,cardIssuedBy,cardholdersName,flightCode,classID)values('2014-04-28',1,'VISA','Alfred Axelsson',32,3); 
insert into Bookings(timeOfBooking,paymentType,cardIssuedBy,cardholdersName,flightCode,classID)values('2014-04-15',1,'Mastercard','Alva Sjöberg',32,3); 
insert into Bookings(timeOfBooking,paymentType,cardIssuedBy,cardholdersName,flightCode,classID)values('2014-04-26',1,'VISA','Alicia Persson',32,3); 
insert into Bookings(timeOfBooking,paymentType,cardIssuedBy,cardholdersName,flightCode,classID)values('2014-04-29',1,'American Express','Elly Pettersson',32,3); 
insert into Bookings(timeOfBooking,paymentType,cardIssuedBy,cardholdersName,flightCode,classID)values('2014-04-22',1,'VISA','Ellen Larsson',32,3); 
insert into Bookings(timeOfBooking,paymentType,cardIssuedBy,cardholdersName,flightCode,classID)values('2014-04-06',1,'VISA','Elsa Jonsson',32,3); 
insert into Bookings(timeOfBooking,paymentType,cardIssuedBy,cardholdersName,flightCode,classID)values('2014-04-03',1,'Mastercard','Tyra Björk',32,3); 
insert into Bookings(timeOfBooking,paymentType,cardIssuedBy,cardholdersName,flightCode,classID)values('2014-04-03',1,'Mastercard','Nova Hermansson',32,3); 
insert into Bookings(timeOfBooking,paymentType,cardIssuedBy,cardholdersName,flightCode,classID)values('2014-04-26',1,'VISA','Elliot Lindholm',32,3); 
insert into Bookings(timeOfBooking,paymentType,cardIssuedBy,cardholdersName,flightCode,classID)values('2014-04-05',1,'Mastercard','Klara Persson',32,3); 
insert into Bookings(timeOfBooking,paymentType,cardIssuedBy,cardholdersName,flightCode,classID)values('2014-04-17',1,'VISA','Julie Andreassen',32,3); 
insert into Bookings(timeOfBooking,paymentType,cardIssuedBy,cardholdersName,flightCode,classID)values('2014-04-11',1,'Mastercard','Harald Olsen',32,3);  
insert into Bookings(timeOfBooking,paymentType,cardIssuedBy,cardholdersName,flightCode,classID)values('2014-04-16',1,'Mastercard','Thomas Svendsen',32,3); 
insert into Bookings(timeOfBooking,paymentType,cardIssuedBy,cardholdersName,flightCode,classID)values('2014-04-28',1,'American Express','Gunn Lie',32,3); 
insert into Bookings(timeOfBooking,paymentType,cardIssuedBy,cardholdersName,flightCode,classID)values('2014-04-13',1,'VISA','Kari Hanssen',32,3); 
insert into Bookings(timeOfBooking,paymentType,cardIssuedBy,cardholdersName,flightCode,classID)values('2014-04-23',1,'American Express','Odd Strand',32,3); 
insert into Bookings(timeOfBooking,paymentType,cardIssuedBy,cardholdersName,flightCode,classID)values('2014-04-22',1,'VISA','Einar Andersen',32,3); 
insert into Bookings(timeOfBooking,paymentType,cardIssuedBy,cardholdersName,flightCode,classID)values('2014-04-04',1,'Mastercard','Sigrid Abrahamsen',32,3); 
insert into Bookings(timeOfBooking,paymentType,cardIssuedBy,cardholdersName,flightCode,classID)values('2014-04-01',1,'VISA','Camilla Hansen',32,3); 
insert into Bookings(timeOfBooking,paymentType,cardIssuedBy,cardholdersName,flightCode,classID)values('2014-04-20',1,'VISA','Camilla Berg',32,3); 
insert into Bookings(timeOfBooking,paymentType,cardIssuedBy,cardholdersName,flightCode,classID)values('2014-04-25',1,'Mastercard','Ole Dahl',32,3); 
insert into Bookings(timeOfBooking,paymentType,cardIssuedBy,cardholdersName,flightCode,classID)values('2014-04-28',1,'VISA','Maria Olsen',32,3); 
insert into Bookings(timeOfBooking,paymentType,cardIssuedBy,cardholdersName,flightCode,classID)values('2014-04-02',1,'VISA','Eirik Amundsen',32,3); 
insert into Bookings(timeOfBooking,paymentType,cardIssuedBy,cardholdersName,flightCode,classID)values('2014-04-27',1,'Diners Club','Randi Bøe',32,3); 
insert into Bookings(timeOfBooking,paymentType,cardIssuedBy,cardholdersName,flightCode,classID)values('2014-04-03',1,'VISA','Kjell Pedersen',32,3); 
insert into Bookings(timeOfBooking,paymentType,cardIssuedBy,cardholdersName,flightCode,classID)values('2014-04-08',1,'VISA','Janne Rasmussen',32,3); 
insert into Bookings(timeOfBooking,paymentType,cardIssuedBy,cardholdersName,flightCode,classID)values('2014-04-19',1,'VISA','Malin Mikkelsen',32,3); 
insert into Bookings(timeOfBooking,paymentType,cardIssuedBy,cardholdersName,flightCode,classID)values('2014-04-03',1,'VISA','Lise Larsen',32,3); 
insert into Bookings(timeOfBooking,paymentType,cardIssuedBy,cardholdersName,flightCode,classID)values('2014-04-25',1,'VISA','Tone Nielsen',32,3); 
insert into Bookings(timeOfBooking,paymentType,cardIssuedBy,cardholdersName,flightCode,classID)values('2014-04-03',1,'VISA','Thomas Andersen',32,3); 
insert into Bookings(timeOfBooking,paymentType,cardIssuedBy,cardholdersName,flightCode,classID)values('2014-04-16',1,'VISA','Stian Nilsen',32,3); 
insert into Bookings(timeOfBooking,paymentType,cardIssuedBy,cardholdersName,flightCode,classID)values('2014-04-05',1,'Mastercard','Stian Pettersen',32,3); 
insert into Bookings(timeOfBooking,paymentType,cardIssuedBy,cardholdersName,flightCode,classID)values('2014-04-19',1,'American Express','Olav Jensen',32,3); 
insert into Bookings(timeOfBooking,paymentType,cardIssuedBy,cardholdersName,flightCode,classID)values('2014-04-12',1,'VISA','Silje Hanssen',32,3); 
insert into Bookings(timeOfBooking,paymentType,cardIssuedBy,cardholdersName,flightCode,classID)values('2014-04-07',1,'American Express','Per Pedersen',32,3); 
insert into Bookings(timeOfBooking,paymentType,cardIssuedBy,cardholdersName,flightCode,classID)values('2014-04-17',1,'Mastercard','Irene Larsen',32,3); 
insert into Bookings(timeOfBooking,paymentType,cardIssuedBy,cardholdersName,flightCode,classID)values('2014-04-16',1,'VISA','Eivind Olsen',32,3); 
insert into Bookings(timeOfBooking,paymentType,cardIssuedBy,cardholdersName,flightCode,classID)values('2014-04-12',1,'VISA','Einar Christensen',32,3); 
insert into Bookings(timeOfBooking,paymentType,cardIssuedBy,cardholdersName,flightCode,classID)values('2014-04-07',1,'VISA','Terje Kristiansen',32,3); 
insert into Bookings(timeOfBooking,paymentType,cardIssuedBy,cardholdersName,flightCode,classID)values('2014-04-05',1,'Mastercard','Anne Andreassen',32,3); 
insert into Bookings(timeOfBooking,paymentType,cardIssuedBy,cardholdersName,flightCode,classID)values('2014-04-03',1,'VISA','Lars Andersen',32,3); 
insert into Bookings(timeOfBooking,paymentType,cardIssuedBy,cardholdersName,flightCode,classID)values('2014-04-14',1,'VISA','Hilde Henriksen',32,3); 
insert into Bookings(timeOfBooking,paymentType,cardIssuedBy,cardholdersName,flightCode,classID)values('2014-04-09',1,'VISA','Unni Olsen',32,3); 
insert into Bookings(timeOfBooking,paymentType,cardIssuedBy,cardholdersName,flightCode,classID)values('2014-04-03',1,'VISA','Julie Johansen',32,3); 
insert into Bookings(timeOfBooking,paymentType,cardIssuedBy,cardholdersName,flightCode,classID)values('2014-04-19',1,'VISA','Julie Jørgensen',32,3); 
insert into Bookings(timeOfBooking,paymentType,cardIssuedBy,cardholdersName,flightCode,classID)values('2014-04-03',1,'Diners Club','Alf Moe',32,3); 
insert into Bookings(timeOfBooking,paymentType,cardIssuedBy,cardholdersName,flightCode,classID)values('2014-04-25',1,'VISA','Jørgen Kristensen',32,3); 
insert into Bookings(timeOfBooking,paymentType,cardIssuedBy,cardholdersName,flightCode,classID)values('2014-04-09',1,'VISA','Anne Larsen',32,3); 
insert into Bookings(timeOfBooking,paymentType,cardIssuedBy,cardholdersName,flightCode,classID)values('2014-04-06',1,'VISA','Eva Moen',32,3); 
insert into Bookings(timeOfBooking,paymentType,cardIssuedBy,cardholdersName,flightCode,classID)values('2014-04-10',1,'VISA','Terje Olsen',32,3); 
insert into Bookings(timeOfBooking,paymentType,cardIssuedBy,cardholdersName,flightCode,classID)values('2014-04-03',1,'VISA','Astrid Kristiansen',32,3); 
insert into Bookings(timeOfBooking,paymentType,cardIssuedBy,cardholdersName,flightCode,classID)values('2014-04-21',1,'VISA','Linda Hansen',32,3); 
insert into Bookings(timeOfBooking,paymentType,cardIssuedBy,cardholdersName,flightCode,classID)values('2014-04-07',1,'Mastercard','Torill Andersen',32,3); 
insert into Bookings(timeOfBooking,paymentType,cardIssuedBy,cardholdersName,flightCode,classID)values('2014-04-13',1,'VISA','Karin Vik',32,3); 
insert into Bookings(timeOfBooking,paymentType,cardIssuedBy,cardholdersName,flightCode,classID)values('2014-04-04',1,'VISA','Tonje Holm',32,3); 
insert into Bookings(timeOfBooking,paymentType,cardIssuedBy,cardholdersName,flightCode,classID)values('2014-04-17',1,'Diners Club','Inger Haugen',32,3); 
insert into Bookings(timeOfBooking,paymentType,cardIssuedBy,cardholdersName,flightCode,classID)values('2014-04-22',1,'VISA','Solveig Olsen',32,3); 
insert into Bookings(timeOfBooking,paymentType,cardIssuedBy,cardholdersName,flightCode,classID)values('2014-04-12',1,'VISA','Tore Nygård',32,3); 
insert into Bookings(timeOfBooking,paymentType,cardIssuedBy,cardholdersName,flightCode,classID)values('2014-04-25',1,'Diners Club','Øyvind Nygård',32,3); 
insert into Bookings(timeOfBooking,paymentType,cardIssuedBy,cardholdersName,flightCode,classID)values('2014-04-24',1,'Mastercard','Ragnhild Jakobsen',32,3); 
insert into Bookings(timeOfBooking,paymentType,cardIssuedBy,cardholdersName,flightCode,classID)values('2014-04-01',1,'Diners Club','Tore Danielsen',32,3); 
insert into Bookings(timeOfBooking,paymentType,cardIssuedBy,cardholdersName,flightCode,classID)values('2014-04-15',1,'VISA','Tobias Nilsen',32,3); 
insert into Bookings(timeOfBooking,paymentType,cardIssuedBy,cardholdersName,flightCode,classID)values('2014-04-19',1,'Mastercard','Elin Karlsen',32,3); 
insert into Bookings(timeOfBooking,paymentType,cardIssuedBy,cardholdersName,flightCode,classID)values('2014-04-10',1,'VISA','Gerd Haugen',32,3); 
insert into Bookings(timeOfBooking,paymentType,cardIssuedBy,cardholdersName,flightCode,classID)values('2014-04-11',1,'American Express','Arne Berge',32,3); 
insert into Bookings(timeOfBooking,paymentType,cardIssuedBy,cardholdersName,flightCode,classID)values('2014-04-03',1,'Mastercard','Aron Þórisson',32,3);  
insert into Bookings(timeOfBooking,paymentType,cardIssuedBy,cardholdersName,flightCode,classID)values('2014-04-21',1,'VISA','Páll Þórisson',32,3); 
insert into Bookings(timeOfBooking,paymentType,cardIssuedBy,cardholdersName,flightCode,classID)values('2014-04-10',1,'American Express','Róbert Emilsson',32,3); 
insert into Bookings(timeOfBooking,paymentType,cardIssuedBy,cardholdersName,flightCode,classID)values('2014-04-12',1,'VISA','Ágúst Róbertsson',32,3); 
insert into Bookings(timeOfBooking,paymentType,cardIssuedBy,cardholdersName,flightCode,classID)values('2014-04-25',1,'Mastercard','Bragi Vilhjálmsson',32,3); 
insert into Bookings(timeOfBooking,paymentType,cardIssuedBy,cardholdersName,flightCode,classID)values('2014-04-03',1,'VISA','Þórir Brekason',32,3); 
insert into Bookings(timeOfBooking,paymentType,cardIssuedBy,cardholdersName,flightCode,classID)values('2014-04-14',1,'VISA','Auður Viðarsdóttir',32,3); 
insert into Bookings(timeOfBooking,paymentType,cardIssuedBy,cardholdersName,flightCode,classID)values('2014-04-07',1,'American Express','Líf Arnardóttir',32,3); 
insert into Bookings(timeOfBooking,paymentType,cardIssuedBy,cardholdersName,flightCode,classID)values('2014-04-12',1,'VISA','Ragnheiður Sigurðardóttir',32,3); 
insert into Bookings(timeOfBooking,paymentType,cardIssuedBy,cardholdersName,flightCode,classID)values('2014-04-27',1,'American Express','Andri Freysson',32,3); 
insert into Bookings(timeOfBooking,paymentType,cardIssuedBy,cardholdersName,flightCode,classID)values('2014-04-10',1,'Diners Club','Ágústa Þorvaldsdóttir',32,3); 
insert into Bookings(timeOfBooking,paymentType,cardIssuedBy,cardholdersName,flightCode,classID)values('2014-04-04',1,'VISA','Andri Arnarson',32,3); 
insert into Bookings(timeOfBooking,paymentType,cardIssuedBy,cardholdersName,flightCode,classID)values('2014-04-23',1,'VISA','Darri Tryggvason',32,3); 
insert into Bookings(timeOfBooking,paymentType,cardIssuedBy,cardholdersName,flightCode,classID)values('2014-04-20',1,'VISA','Ólafur Friðriksson',32,3); 
insert into Bookings(timeOfBooking,paymentType,cardIssuedBy,cardholdersName,flightCode,classID)values('2014-04-04',1,'Mastercard','Valgerður Kjartansdóttir',32,3); 
insert into Bookings(timeOfBooking,paymentType,cardIssuedBy,cardholdersName,flightCode,classID)values('2014-04-06',1,'VISA','Gísli Arnarson',32,3); 
insert into Bookings(timeOfBooking,paymentType,cardIssuedBy,cardholdersName,flightCode,classID)values('2014-04-08',1,'VISA','Hulda Brekadóttir',32,3); 
insert into Bookings(timeOfBooking,paymentType,cardIssuedBy,cardholdersName,flightCode,classID)values('2014-04-24',1,'VISA','Trausti Þórarinsson',32,3); 
insert into Bookings(timeOfBooking,paymentType,cardIssuedBy,cardholdersName,flightCode,classID)values('2014-04-14',1,'Mastercard','Ásdís Sindradóttir',32,3); 
insert into Bookings(timeOfBooking,paymentType,cardIssuedBy,cardholdersName,flightCode,classID)values('2014-04-08',1,'VISA','Hanna Kristinsdóttir',32,3); 
insert into Bookings(timeOfBooking,paymentType,cardIssuedBy,cardholdersName,flightCode,classID)values('2014-04-25',1,'American Express','Guðmundur Davíðsson',32,3); 
insert into Bookings(timeOfBooking,paymentType,cardIssuedBy,cardholdersName,flightCode,classID)values('2014-04-21',1,'VISA','Ari Arason',32,3); 
insert into Bookings(timeOfBooking,paymentType,cardIssuedBy,cardholdersName,flightCode,classID)values('2014-04-18',1,'Mastercard','Rúnar Logason',32,3); 
insert into Bookings(timeOfBooking,paymentType,cardIssuedBy,cardholdersName,flightCode,classID)values('2014-04-16',1,'Mastercard','Bragi Kristinsson',32,3); 
insert into Bookings(timeOfBooking,paymentType,cardIssuedBy,cardholdersName,flightCode,classID)values('2014-04-14',1,'VISA','Þórir Heiðarsson',32,3); 
insert into Bookings(timeOfBooking,paymentType,cardIssuedBy,cardholdersName,flightCode,classID)values('2014-04-23',1,'Mastercard','Jóhann Baldursson',32,3); 
insert into Bookings(timeOfBooking,paymentType,cardIssuedBy,cardholdersName,flightCode,classID)values('2014-04-02',1,'American Express','Eva Reynisdóttir',32,3); 
insert into Bookings(timeOfBooking,paymentType,cardIssuedBy,cardholdersName,flightCode,classID)values('2014-04-10',1,'VISA','Árni Þórisson',32,3); 
insert into Bookings(timeOfBooking,paymentType,cardIssuedBy,cardholdersName,flightCode,classID)values('2014-04-29',1,'VISA','Bjarki Arnarson',32,3); 
insert into Bookings(timeOfBooking,paymentType,cardIssuedBy,cardholdersName,flightCode,classID)values('2014-04-18',1,'VISA','Þór Bergmannsson',32,3); 
insert into Bookings(timeOfBooking,paymentType,cardIssuedBy,cardholdersName,flightCode,classID)values('2014-04-04',1,'Mastercard','Einar Hermannsson',32,3); 
insert into Bookings(timeOfBooking,paymentType,cardIssuedBy,cardholdersName,flightCode,classID)values('2014-04-18',1,'Mastercard','Guðrún Aðalsteinsdóttir',32,3); 
insert into Bookings(timeOfBooking,paymentType,cardIssuedBy,cardholdersName,flightCode,classID)values('2014-04-21',1,'Mastercard','Guðmundur Daníelsson',32,3); 
insert into Bookings(timeOfBooking,paymentType,cardIssuedBy,cardholdersName,flightCode,classID)values('2014-04-09',1,'VISA','Ólafur Sverrisson',32,3); 
insert into Bookings(timeOfBooking,paymentType,cardIssuedBy,cardholdersName,flightCode,classID)values('2014-04-28',1,'American Express','Guðbjörg Bergmannsdóttir',32,3); 
insert into Bookings(timeOfBooking,paymentType,cardIssuedBy,cardholdersName,flightCode,classID)values('2014-04-07',1,'Mastercard','Kristín Káradóttir',32,3); 
insert into Bookings(timeOfBooking,paymentType,cardIssuedBy,cardholdersName,flightCode,classID)values('2014-04-20',1,'VISA','Sigurður Bergmannsson',32,3); 
insert into Bookings(timeOfBooking,paymentType,cardIssuedBy,cardholdersName,flightCode,classID)values('2014-04-21',1,'Mastercard','Halldór Atlason',32,3); 
insert into Bookings(timeOfBooking,paymentType,cardIssuedBy,cardholdersName,flightCode,classID)values('2014-04-16',1,'VISA','Ingvar Kristófersson',32,3); 
insert into Bookings(timeOfBooking,paymentType,cardIssuedBy,cardholdersName,flightCode,classID)values('2014-04-19',1,'VISA','Katrín Björnsdóttir',32,3); 
insert into Bookings(timeOfBooking,paymentType,cardIssuedBy,cardholdersName,flightCode,classID)values('2014-04-19',1,'Mastercard','Bára Eyþórsdóttir',32,3); 
insert into Bookings(timeOfBooking,paymentType,cardIssuedBy,cardholdersName,flightCode,classID)values('2014-04-04',1,'American Express','Stefanía Ingólfsdóttir',32,3); 
insert into Bookings(timeOfBooking,paymentType,cardIssuedBy,cardholdersName,flightCode,classID)values('2014-04-16',1,'VISA','Ólöf Arnórsdóttir',32,3); 
insert into Bookings(timeOfBooking,paymentType,cardIssuedBy,cardholdersName,flightCode,classID)values('2014-04-06',1,'VISA','Þóra Jónsdóttir',32,3); 
insert into Bookings(timeOfBooking,paymentType,cardIssuedBy,cardholdersName,flightCode,classID)values('2014-04-22',1,'VISA','Sigríður Ívarsdóttir',32,3); 
insert into Bookings(timeOfBooking,paymentType,cardIssuedBy,cardholdersName,flightCode,classID)values('2014-04-06',1,'Mastercard','Friðrik Antonsson',32,3); 
insert into Bookings(timeOfBooking,paymentType,cardIssuedBy,cardholdersName,flightCode,classID)values('2014-04-21',1,'VISA','Bryndís Gunnarsdóttir',32,3); 
insert into Bookings(timeOfBooking,paymentType,cardIssuedBy,cardholdersName,flightCode,classID)values('2014-04-23',1,'VISA','Sóley Steinsdóttir',32,3); 
insert into Bookings(timeOfBooking,paymentType,cardIssuedBy,cardholdersName,flightCode,classID)values('2014-04-04',1,'Mastercard','Margrét Alexandersdóttir',32,3); 
insert into Bookings(timeOfBooking,paymentType,cardIssuedBy,cardholdersName,flightCode,classID)values('2014-04-09',1,'Diners Club','Þórunn Snæsdóttir',32,3); 
insert into Bookings(timeOfBooking,paymentType,cardIssuedBy,cardholdersName,flightCode,classID)values('2014-04-15',1,'Diners Club','Ragnheiður Axelsdóttir',32,3); 
insert into Bookings(timeOfBooking,paymentType,cardIssuedBy,cardholdersName,flightCode,classID)values('2014-04-21',1,'VISA','Elín Steinsdóttir',32,3); 
insert into Bookings(timeOfBooking,paymentType,cardIssuedBy,cardholdersName,flightCode,classID)values('2014-04-04',1,'Diners Club','Margrét Arnardóttir',32,3); 
insert into Bookings(timeOfBooking,paymentType,cardIssuedBy,cardholdersName,flightCode,classID)values('2014-04-09',1,'American Express','Stefán Stefánsson',32,3); 
insert into Bookings(timeOfBooking,paymentType,cardIssuedBy,cardholdersName,flightCode,classID)values('2014-04-06',1,'VISA','Ragnheiður Bjarnadóttir',32,3); 
insert into Bookings(timeOfBooking,paymentType,cardIssuedBy,cardholdersName,flightCode,classID)values('2014-04-27',1,'American Express','Magnús Árnason',32,3); 
insert into Bookings(timeOfBooking,paymentType,cardIssuedBy,cardholdersName,flightCode,classID)values('2014-04-13',1,'VISA','Hildur Gunnlaugsdóttir',32,3); 
insert into Bookings(timeOfBooking,paymentType,cardIssuedBy,cardholdersName,flightCode,classID)values('2014-04-15',1,'VISA','Kári Birkisson',32,3); 
insert into Bookings(timeOfBooking,paymentType,cardIssuedBy,cardholdersName,flightCode,classID)values('2014-04-03',1,'VISA','Bjarni Darrason',32,3); 
insert into Bookings(timeOfBooking,paymentType,cardIssuedBy,cardholdersName,flightCode,classID)values('2014-04-13',1,'VISA','Katrín Þórarinsdóttir',32,3); 
insert into Bookings(timeOfBooking,paymentType,cardIssuedBy,cardholdersName,flightCode,classID)values('2014-04-13',1,'VISA','Ingibjörg Guðlaugsdóttir',32,3);